channels:
  - conda-forge

dependencies:
  - python=3.9.0             
  - pip=21.2.3 
  - firefox=127.0.2         
  - pip:
    - rpaframework==28.6.3
    - pandas==2.2.3
    - selenium==4.15.2
    - get-gecko-driver==1.3.13