channels:
  - conda-forge

dependencies:
  - python=3.9.0             
  - pip=21.2.3 
  - firefox=117.0.2 
  - libxrender
  - libxext
  - libxshmfence       
  - pip:
    - rpaframework==28.6.3
    - pandas==2.2.3
    - selenium==4.15.2
    - webdriver-manager==4.0.2